### PR TITLE
Highlight `-mode(compile)`

### PR DESCRIPTION
**Pull request by habamax**
image

### CODE REVIEW

**Comment by hcs42** [comment]
Thank you for your PR!

Could you amend this commit, and add this attribute to [`test/test_syntax.erl`](https://github.com/vim-erlang/vim-erlang-runtime/blob/f7d4bbdcff675000d4345d9834cc7d825a84ed3f/test/test_syntax.erl#L209)? I suggest the following:

```erlang
[...]
-behavior(Behaviour).
-file(File, Line).
-feature(maybe_expr, enable).

% Specified in https://www.erlang.org/doc/man/escript.
-mode(compile).

% Unknown attribute (not highlighted).
-other(File, Line).
```

**Comment by habamax** [comment]
Pushed another commit here, I remember github was able to rebase/squash commits while merging PRs.

**Comment by habamax** [comment]
And I don't have to create PR against vim/vim, right? Eventually you will do it? :)

**Comment by hcs42** [comment]
> Pushed another commit here, I remember github was able to rebase/squash commits while merging PRs.

Yes, although it is not perfect: https://github.com/vim-erlang/vim-erlang-runtime/pull/53#issuecomment-1242775224

You use the same e-mail address in your commit and in GitHub, so I used GitHub's "Squash and merge" button. The resulting commit looks good. This also gave me a chance to add `Fix #56` to the commit message :) But here is another small weirdness: the PR page shows your original two commits conspicuously, but it shows the final commit less conspicuously.

> And I don't have to create PR against vim/vim, right? Eventually you will do it? :)

Indeed. Vim 9.1 was recently released, and Vim's maintainer asked the plugin maintainers beforehand to create PRs about any outstanding changes. So I will create a PR in vim/vim at the latest before Vim 9.2 (or 10.0) is released.

**Pull request merged**
