### PR TITLE
Add installation instructions for vim-plug

### LINKED ISSUE #29: Add instructions for installing vim-erlang-runtime with vim-plug
vim-plug is a minimal plugin manager

installation of vim-erlang-runtime with vim-plug is simple, add it to the readme.

### PR DESCRIPTION
**Pull request by theRemix**
resolves #29

### CODE REVIEW

**Comment by hcs42** [comment]
Just a tiny request: could you change the commit message to "Add installation instructions for vim-plug"? (To match the conventions of using the imperative mode and starting with a capital letter, and to make it a bit shorter.)

Otherwise I'm happy to merge.

**Comment by theRemix** [comment]
@hcs42 Updated the pr title

**Comment by aerosol** [comment]
@theRemix amend the commit message please

**Comment by theRemix** [comment]
@aerosol done :+1:

**Comment by aerosol** [comment]
@theRemix thanks :heart:

**Pull request merged**
