### PR TITLE
Add a few more syntax classes (try 2)

### PR DESCRIPTION
**Pull request by choptastic**
Hi this adds a few things I wanted to distinguish in my own syntax highlighting.

* Add `erlangAnonymousVariable` class, distinguishing it from the normal `erlangVariable`

* highlight the `=<<` part of something like `Var=<<"binary">>` (since
  that is never valid as '=<' is already an operator.

### CODE REVIEW

**Comment by hcs42** [comment]
Hi,

1.  The following expressions are valid, even though they contain `=<<`:

    ```
    Var=<<<"binary">>  % Same as: Var =< <<"binary">>
    Var==<<"binary">>  % Same as: Var == <<"binary">>
    ```

    The commit highlights the first one as an error. It does not highlight the second one.

    Could you modify the commit to highlight `=<<` only when it is invalid? This seems to do the trick:

    ```
    syn match erlangEqualsBinary '=<<\%(<\)\@!'
    ```

2.  Could you update `test/test_syntax.erl` to contain examples with `=<<`? It should contain at least one invalid expression (which is highlighted as an error), and the two examples above (which are not).

    I just updated `test/test_syntax.erl` because when I looked into it, I realized that the section numbers have changed since that file was written, so I updated them. Thus, please make sure that you refresh your `master` branch before modify `test_syntax.erl`. I would put the examples into the 7."11 Term Comparisons" section (because they are related to `=<`).

3.  When you update your commit, please don't close this pull request and open another one. Modify your commit locally and push it to your `master` branch on GitHub. GitHub will automatically update your pull request.

**Comment by choptastic** [comment]
Hi! Thanks for the reply. I will indeed do these, thanks so much for the fast reply!

**Comment by choptastic** [comment]
The requested changes have been done.  Please let me know if anything else needs to be changed.

**Comment by hcs42** [comment]
Thank you for your contribution!

**Comment by hcs42** [comment]
Nlote: I tried GitHub's "Squash and merge" button, which almost worked, and produced this commit: https://github.com/vim-erlang/vim-erlang-runtime/commit/efae605a915da3e8de4def811296191dd115ef64

However, it modified your e-mail address from sigmastar to gmail. So I squashed the commits using Git commands to keep your sigmastar e-mail address in the commits, and forced pushed that to the `master` branch: https://github.com/vim-erlang/vim-erlang-runtime/commit/8fd6630dca9acf399e19aadbb085802f4ab7aa22

The content is the same; I just wanted to let you know.

**Pull request merged**
